### ISSUE TITLE
Ethereum Prisoners rong faction (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#39]
Now that i made u familiar with them ...all say the faction each of them belong:

There are the following factions:
*Cenarion Expedition
*Consortium
*Keepers of Time
*Lower City
*The Sha'tar
*Sporeggar

somehow they all have Faction 35 in the db...and it's incorrect there for the script that casts the spell will give a console error "incorrect expected faction" or smth like that...i fixed it in the past...by adding the correct individual factions for each of them

**Comment by Salja** [comment]
Thanks fix cone next week

**Comment by Salja** [comment]
Ethereum Prisoners Entry 20520 have not faction 35 in my database

**Comment by Mibu86** [comment]
u dont understand :P m talking about:
![wowscrnshot_062614_004415](https://cloud.githubusercontent.com/assets/6356589/3392217/261d9c18-fcb2-11e3-8f42-de98e4c8e776.jpg)
that's one of them...
and the Script error because of the rong faction
![untitled](https://cloud.githubusercontent.com/assets/6356589/3392241/62bbc56e-fcb2-11e3-95bb-097bbb0117fe.png)
So in order to correct myself here are the exact creatures with rong factions for the script to work:

Rescued Cenarion Expedition Druid (ID: 22810) - gives 500 reputation towards Cenarion Expedition 
Rescued Lower City Brute (ID: 22811) - gives 500 reputation towards Lower City 
Rescued Sha'tar Vindicator (ID: 22812) - gives 500 reputation towards The Sha'tar 
Rescued Consortium Dealer (ID: 22813) - gives 500 reputation towards The Consortium (faction ID: 
Rescued Sporeggar Scout (ID: 22814) - gives 500 reputation towards Sporeggar 
Rescued Keepers of Time Custodian (ID: 22815) - gives 500 reputation towards Keepers of Time 

I fixxed once but i cant remember the correct factions atm i also opened another issue request on those Pink Globe prisons...because they only re spawn on server restart
This is the only way players can farm reputation beyond a certain point without having to do HC and raids with those factions...all they need to do is get Consortium reputation..farm those Ethereum    Jailors witch spawns u fixed for the keys..and after that just farm these prisons...some of them releases this prisoners witch reward xp...some agro miniboses give nice blue items...good for starting gear and increasing enchanting skill by disenchanting them.
So need to fix it...

**Comment by Salja** [comment]
thanks =)

**Comment by Salja** [comment]
Fixed about respawn time i will check the other issue

**Comment by Mibu86** [comment]
Not fixed...yes no more error in the console..about wrong faction..but also...they don't cast the Reputation spell on the player that releases them...actually it do-sent cast it at all... broken maybe?

**Comment by Salja** [comment]
hmm other is handel by scripts can you tell me how its works you click on the bubble npc come and than ? or maybe you found a youtube video ?

**Comment by Salja** [comment]
hmm all is right i have no idea way he not cast the spell hmm need some more debug

**Comment by Mibu86** [comment]
i see you closed this...are they casting the spell now?

**Comment by Salja** [comment]
I reopen he not cast the spell i think sd2 problem need more look i have no idea way im close it xD :-)
